 <?php
 $ListItems = Array(
     "Region-0" => Array(
         'Contact Minnesota',
         'Contact Iowa',
         'Contact Colorado',
         'Contact Kansas',
         'Contact Missouri',
         'Contact Nebraska',
         'Contact North Dakota',
         'Contact South Dakota'),
     "Region-1" => Array(
         'Contact Connecticut',
         'Contact Eastern Massachusetts',
         'Contact Western Massachusetts',
         'Contact Maine',
         'Contact New Hampshire',
         'Contact Rhode Island',
         'Contact Vermont'),
     "Region-2" => Array(
         'Contact Eastern New York',
         'Contact New York City - Long Island',
         'Contact Northern New Jersey',
         'Contact Northern New York',
         'Contact Southern New Jersey',
         'Contact Western New York'),
     "Region-3" => Array(
         'Contact Delaware',
         'Contact Eastern Pennsylvania',
         'Contact Maryland - DC',
         'Contact Western Pennsylvania'),
     "Region-4" => Array(
         'Contact Alabama',
         'Contact Georgia',
         'Contact Kentucky',
         'Contact North Carolina',
         'Contact Northern Florida',
         'Contact South Carolina',
         'Contact Southern Florida',
         'Contact West Central Flordia',
         'Contact Tennessee',
         'Contact Virginia',
         'Contact Puerto Rico',
         'Contact Virgin Islands'),
     "Region-5" => Array(
         'Contact Arkansas',
         'Contact Louisiana',
         'Contact Mississippi',
         'Contact New Mexico',
         'Contact North Texas',
         'Contact Oklahoma',
         'Contact South Texas',
         'Contact West Texas'),
     "Region-6" => Array(
         'Contact East Bay',
         'Contact Los Angeles',
         'Contact Orange County',
         'Contact Santa Barbara',
         'Contact Santa Clara Valley',
         'Contact San Diego',
         'Contact San Fransisco',
         'Contact San Joaquin Valley',
         'Contact Sacreamento Valley',
         'Contact Pacific'),
     "Region-7" => Array(
         'Contact Arizona',
         'Contact Eastern Washington',
         'Contact Idaho',
         'Contact Montana',
         'Contact Nevada',
         'Contact Oregon',
         'Contact Utah',
         'Contact Western Washington',
         'Contact Wyoming',
         'Contact Alaska'),
     "Region-8" => Array(
         'Contact Michigan',
         'Contact Ohio',
         'Contact West Virginia'),
     "Region-9" => Array(
         'Contact Illinois',
         'Contact Indiana',
         'Contact Wisconsin'),
     "Canada" => Array(
         'Contact Maritime',
         'Contact Newfoundland/Labrador',
         'Contact Prince Edward Island',
         'Contact Quebec',
         'Contact Ontario North',
         'Contact Ontario South',
         'Contact Ontario East',
         'Contact Greater Toronto Area',
         'Contact Manitoba',
         'Contact Saskatchewan',
         'Contact Alberta',
         'Contact British Columbia',
         'Contact Northern Territories'),
     "Mode-Counts" => Array(
         'Make 1 CW contact',
         'Make 5 CW contacts',
         'Make 1 SSB contact',
         'Make 5 SSB contacts',
         'Make 1 AM contact',
         'Make 5 AM contacts',
         'Make 1 digital contact',
         'Make 5 digital contacts',
         'Make 1 satellite contact',
         'Make 5 satellite contacts'),
     "Band" => Array(
         'Make contact on 160m',
         'Make contact on 80m',
         'Make contact on 40m',
         'Make contact on 20m',
         'Make contact on 15m',
         'Make contact on 10m',
         'Make contact on 6m',
         'Make contact on 2m',
         'Make contact on 1.25m',
         'Make contact on 70cm'),
    "Protocol-Special" => Array(
         'Make contact with CW',
         'Make contact with AM',
         'Make contact with SSB',
         'Make contact with AM',
         'Make contact with FM',
         'Make contact with FT4/8',
         'Make contact with PSK31',
         'Make contact with APRS'),
    "Location" => Array(
         'Make contact with Maritime station',
         'Make contact with Mobile station',
         'Make contact with Aeronautical station',
         'Make contact with International Space Station',
         'Make contact with a Military Station',
         'Make contact with a National Park',
         'Make contact with a State Park',
         'Make contact with a Summit on the Air',
         'Make contact with an Island on the Air',
         'Make contact with a Lighthouse/Lightship',
         'Make contact with a Special Event Station',
         'Make contact with W1AW'),
    "Club-Challenges" => Array(
        'Make contact with 1 club member',
        'Make contact with 5 club members',
        'Make contact with 10 club members',
        'Make contact with a nearby club',
        'Make contact with a distant club',
        'Make contact with a national club',
        'Make contact with an international club'),
    "Counts" => Array(
        'Make 5 contacts in 10 minutes',
        'Make 10 contacts in 10 minutes',
        'Make 30 contacts in an hour',
        'Make 100 contacts in 3 hours',
        'Make 300 contacts in 6 hours',
        'Make 500 contacts in 8 hours',
        'make 1000 contacts in 24 hours'),
    "Station-Classes" => Array(
        'Make contact with a Class A station',
        'Make contact with a Class B station',
        'Make contact with a Class C station',
        'Make contact with a Class D station',
        'Make contact with a class E station',
        'Make contact with a class F station',
        'Make contact with a QRP station'),
    "Bonus-Points" => Array(
        'Use 100% Emergency Power',
        'Obtain publicity from local media',
        'Operate from a public location',
        'Provide public information',
        'Originate a Formal Message to Section Manager',
        'Relay a formal message',
        'Make a satellite QSO',
        'Make 5 contacts using alternate power source',
        'Copy a W1AW bulletin',
        'Submit field day entry via web',
        'Participate with a youth',
        'Promote your operation via social media',
        'Declare a safety officer for your operation')
     );
 ?>
